# Initial state of the FSM
initial_state: "LANE_FOLLOWING"
events: #Maps from subscribing topic to signal ids
  at_stop_line:
    topic: "stop_line_filter_node/at_stop_line"
    msg_type: "BoolStamped"
    trigger: True
#  intersection_go:
#    topic: "simple_coordinator_node/intersection_go"
#    msg_type: "BoolStamped"
#    trigger: True

# Not sure which one of these we need to use
  intersection_done:
    topic: "open_loop_intersection_control_node/intersection_done"
    msg_type: "BoolStamped"
    trigger: True
#  intersection_done:
#    topic: "logic_gate_node/intersection_done_and_not_parallel_autonomy"
#    msg_type: "BoolStamped"
#    trigger: True
  obstacle_detection:
    topic: "obstacle_safety_node/object_too_close"
    msg_type: "BoolStamped"
    trigger: True
  obstacle_cleared:
    topic: "obstacle_safety_node/object_too_close"
    msg_type: "BoolStamped"
    trigger: False

# Define nodes 
nodes:
  decoder_node: "decoder_node/switch"
# anti_instagram_node: "anti_instagram/switch"
  line_detector_node: "line_detector_node/switch"
  lane_filter_node: "lane_filter_node/switch"
  stop_line_filter_node: "stop_line_filter_node/switch"
  framerate_high: "camera_node/framerate_high_switch"

# Define state transitions
states:
  LANE_FOLLOWING:
    transitions:
      at_stop_line: "INTERSECTION_CONTROL"
      obstacle_detection: "AVOID_OBSTACLE"
    active_nodes:
      - lane_filter_node
      - line_detector_node
      - stop_line_filter_node
      - decoder_node
  INTERSECTION_CONTROL:
    transitions:
      intersection_done: "LANE_FOLLOWING"
    active_nodes:
      - line_detector_node
      - lane_filter_node
      - decoder_node
  AVOID_OBSTACLE:
    transitions:
      obstacle_cleared: "LANE_FOLLOWING"
    active_nodes:
      - decoder_node
